"""Generic, domain-agnostic resource harmonization framework.

Provides:
- Sanitization & Normalization pipelines (whitespace, de-accenting, Unicode NFKC/NFKD, typos)
- Resource Fingerprinting & hierarchical Merkle digests (atomic, ordered, unordered/set, compound)
- Syntactic, Semantic Vector, Agent/LLM, and Composite Comparators
- HarmonizationRegistry for indexing, search, deduplication, and matching
- Domain models for Categories, Codes, CodeLists, Questions, and Concepts
"""

from .comparators import (
    AgentComparator,
    AgentComparisonResult,
    AgentDecision,
    ComparisonProfile,
    ComparisonResult,
    ContentComparator,
    DefaultTfIdfEmbeddingProvider,
    EmbeddingProvider,
    ExactComparator,
    LevenshteinComparator,
    QuestionComparator,
    RuleBasedMockAgentComparator,
    SemanticVectorComparator,
    SequenceMatcherComparator,
    TokenJaccardComparator,
    TransformationAction,
    TransformationAdvice,
    VariableComparator,
    VariableComparisonResult,
    VariableComparisonWeights,
    WeightedAttributeComparator,
    compare_codelists,
    compare_questions,
    compare_resources,
    compare_variables,
)
from .domains import (
    CanonicalDataType,
    DataType,
    DataTypeVocabulary,
    HarmonizedCategory,
    HarmonizedCode,
    HarmonizedCodeItem,
    HarmonizedCodeList,
    HarmonizedConcept,
    HarmonizedNumericDomain,
    HarmonizedQuestion,
    HarmonizedTextDomain,
    HarmonizedUniverse,
    HarmonizedValueDomain,
    HarmonizedVariable,
    QuantityKind,
    SentinelType,
    UnitOfMeasure,
    ValueDomainKind,
)
from .examples import CaseBankLoader, HarmonizerTestCase
from .explorer import generate_harmonizer_explorer_html, launch_explorer
from .fingerprinter import ResourceFingerprinter
from .identifiers import (
    IdentifierKind,
    ResourceIdentifier,
    parse_identifier,
)
from .models import (
    ContentFingerprint,
    ContentSignature,
    HarmonizableResource,
    HarmonizationMatch,
    MatchType,
)
from .normalizer import (
    NormalizationPreset,
    NormalizerConfig,
    TextNormalizer,
    UnicodeForm,
)
from .registry import HarmonizationRegistry
from .review import CuratedCrosswalk, HumanReviewQueue, ReviewItem
from .sanitizer import SanitizerConfig, TextSanitizer

__all__ = [
    "AgentComparator",
    "AgentComparisonResult",
    "AgentDecision",
    "CanonicalDataType",
    "CaseBankLoader",
    "ComparisonProfile",
    "ComparisonResult",
    "ContentComparator",
    "ContentFingerprint",
    "ContentSignature",
    "CuratedCrosswalk",
    "DataType",
    "DataTypeVocabulary",
    "DefaultTfIdfEmbeddingProvider",
    "EmbeddingProvider",
    "ExactComparator",
    "HarmonizableResource",
    "HarmonizationMatch",
    "HarmonizationRegistry",
    "HarmonizedCategory",
    "HarmonizedCode",
    "HarmonizedCodeItem",
    "HarmonizedCodeList",
    "HarmonizedConcept",
    "HarmonizedNumericDomain",
    "HarmonizedQuestion",
    "HarmonizedTextDomain",
    "HarmonizedUniverse",
    "HarmonizedValueDomain",
    "HarmonizedVariable",
    "HarmonizerTestCase",
    "HumanReviewQueue",
    "IdentifierKind",
    "LevenshteinComparator",
    "MatchType",
    "NormalizationPreset",
    "NormalizerConfig",
    "QuantityKind",
    "QuestionComparator",
    "ResourceFingerprinter",
    "ResourceIdentifier",
    "ReviewItem",
    "RuleBasedMockAgentComparator",
    "SanitizerConfig",
    "SemanticVectorComparator",
    "SentinelType",
    "SequenceMatcherComparator",
    "TextNormalizer",
    "TextSanitizer",
    "TokenJaccardComparator",
    "TransformationAction",
    "TransformationAdvice",
    "UnicodeForm",
    "UnitOfMeasure",
    "ValueDomainKind",
    "VariableComparator",
    "VariableComparisonResult",
    "VariableComparisonWeights",
    "WeightedAttributeComparator",
    "compare_codelists",
    "compare_questions",
    "compare_resources",
    "compare_variables",
    "generate_harmonizer_explorer_html",
    "launch_explorer",
    "parse_identifier",
]
